### ISSUE TITLE
Change readme Images

### ISSUE THREAD

**Issue by ankittojha** [ankittojha/geeksforgeeks_lpu_official_website#1]
Take latest screenshots from https://geeksforgeekslpu.netlify.app/ and update it in Readme file.

**Comment by HasanAlqaisi** [comment]
Hi,
I updated the images with full screenshots from your website. Please check it out!

**Comment by ankittojha** [comment]
> 

Thank you so much for your contribution.

**Comment by ankittojha** [comment]
Solved
